# Generated by Django 3.0.3 on 2020-03-14 20:20

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200314_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(null=True, upload_to=music.models.image_artist_directory_path),
        ),
    ]
